In [ ]:
import pandas as pd
from datetime import datetime

In [ ]:
# Loading the data
data = pd.read_csv('jadarat_dataset.csv')
data.head()

,job_title,job_date,comp_name,comp_type,comp_size,eco_activity,region,city,benefits,contract,positions,exper,gender,Salary
0,Secretary,2022-10-01,مؤسسة دمك للمقاولات العامة,1,SB,Construction and Real Estate,Eastern,BUQAYQ,0,1,1,0,1,4000.0
1,Salesperson,2022-10-03,شركة محمد سراج عطار وأخويه,1,SB,Trade and Retail,Makkah,JEDDAH,1,1,3,0,0,4000.0
2,Receptionist,2022-10-08,مركز شار لطب الاسنان,1,MA,Trade and Retail,Makkah,JEDDAH,1,1,2,4,1,4000.0
3,Accountant,2022-10-12,شركة اسواق بساتين القصيم,1,MB,Trade and Retail,Riyadh,AR RIYADH,1,1,10,0,2,4000.0
4,Secretary,2022-10-13,شركة السبائك الذهبية للمعادن الثمينة,1,SA,Trade and Retail,Makkah,JEDDAH,1,1,1,2,1,5000.0

In [ ]:
# Checking the columns of this dataset
data.columns

Index(['job_title', 'job_date', 'comp_name', 'comp_type', 'comp_size',
       'eco_activity', 'region', 'city', 'benefits', 'contract', 'positions',
       'exper', 'gender', 'Salary'],
      dtype='object')

In [ ]:
# Checking the details of the dataset
data.info()
print("Rows:", data.shape[0])
print("Columns:", data.shape[1])

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   job_title     1470 non-null   object
 1   job_date      1470 non-null   object
 2   comp_name     1470 non-null   object
 3   comp_type     1470 non-null   int64
 4   comp_size     1470 non-null   object
 5   eco_activity  1470 non-null   object
 6   region        1470 non-null   object
 7   city          1470 non-null   object
 8   benefits      1470 non-null   int64
 9   contract      1470 non-null   int64
 10  positions     1470 non-null   int64
 11  exper         1470 non-null   int64
 12  gender        1470 non-null   int64
 13  Salary        1470 non-null   float64
dtypes: float64(1), int64(6), object(7)
memory usage: 160.9+ KB
Rows: 1470
Columns: 14

In [ ]:
# Checking the missing values
data.isnull().sum()

job_title       0
job_date        0
comp_name       0
comp_type       0
comp_size       0
eco_activity    0
region          0
city            0
benefits        0
contract        0
positions       0
exper           0
gender          0
Salary          0
dtype: int64

In [ ]:
# Checking numerical columns
data.select_dtypes(include='number')

      comp_type  benefits  contract  positions  exper  gender  Salary
0             1         0         1          1      0       1  4000.0
1             1         1         1          3      0       0  4000.0
2             1         1         1          2      4       1  4000.0
3             1         1         1         10      0       2  4000.0
4             1         1         1          1      2       1  5000.0
...         ...       ...       ...        ...    ...     ...     ...
1465          1         1         1          1      4       2  4000.0
1466          1         0         1          1      2       1  4000.0
1467          1         0         1          3      0       2  4500.0
1468          1         0         1          2      4       0  4200.0
1469          1         0         1          3      0       2  4000.0

[1470 rows x 7 columns]

In [ ]:
# Checking categorical columns
data.select_dtypes(include='object')

,job_title,job_date,comp_name,comp_size,eco_activity,region,city
0,Secretary,2022-10-01,مؤسسة دمك للمقاولات العامة,SB,Construction and Real Estate,Eastern,BUQAYQ
1,Salesperson,2022-10-03,شركة محمد سراج عطار وأخويه,SB,Trade and Retail,Makkah,JEDDAH
2,Receptionist,2022-10-08,مركز شار لطب الاسنان,MA,Trade and Retail,Makkah,JEDDAH
3,Accountant,2022-10-12,شركة اسواق بساتين القصيم,MB,Trade and Retail,Riyadh,AR RIYADH
4,Secretary,2022-10-13,شركة السبائك الذهبية للمعادن الثمينة,SA,Trade and Retail,Makkah,JEDDAH
...,...,...,...,...,...,...,...
1465,Analyst,2023-01-23,شركة قوو للتجارة,SB,Technical Services,Riyadh,AR RIYADH
1466,Salesperson,2023-01-23,شركة العلاقات المميزه لتقنية المعلومات شركة شخ...,SB,Technology and Communications,Hail,HAIL
1467,Auditor,2023-01-23,مؤسسة صوادر الغروب للمقاولات,SB,Construction and Real Estate,Riyadh,AR RIYADH
1468,Driver,2023-01-23,شركة ديالوج الجبيل لقواعد الامداد المحدودة,MB,Logistics and Transportation,Eastern,AL JUBAIL
1469,Accountant,2023-01-23,مغاسل نسيم الفل للملابس,U,Tertiary and Services,Eastern,AL KHOBAR

In [ ]:
# Checking the duplicated rows in the dataset
print("Number of duplicate rows:", data.duplicated().sum())

Number of duplicate rows: 83

In [ ]:

d = data[data.duplicated(
    subset=["job_title", "comp_name", "city","positions"],
    keep=False
)]

print(d)

                 job_title    job_date                           comp_name  \
7     Switchboard Operator  2022-10-24       مؤسسة قدور نجد لخدمات الاعاشة
12      Real Estate Broker  2022-10-24                 شركة رحابة العقارية
15      Real Estate Broker  2022-10-24                 شركة رحابة العقارية
19               Secretary  2022-10-24  مكتب المحامي سعد بن درويش آل محفوظ
20                 Analyst  2022-10-24              شركة حديد السد للصناعة
...                    ...         ...                                 ...
1454           Constructor  2023-01-22        مؤسسة فاد الخليجيه للمقاولات
1455           Constructor  2023-01-22        مؤسسة فاد الخليجيه للمقاولات
1457           Constructor  2023-01-22        مؤسسة فاد الخليجيه للمقاولات
1458           Constructor  2023-01-22        مؤسسة فاد الخليجيه للمقاولات
1462               Analyst  2023-01-22    شركة مشفي العبير الطبية المحدودة

      comp_type comp_size                         eco_activity  region  \
7             1        MB                Tertiary and Services  Riyadh
12            1        SA         Construction and Real Estate  Riyadh
15            1        SA         Construction and Real Estate  Riyadh
19            1        SB  Consulting and Profissonal Services  Makkah
20            1        MB             Industrial Manufacturing  Riyadh
...         ...       ...                                  ...     ...
1454          1         L                Tertiary and Services  Riyadh
1455          1         L                Tertiary and Services  Riyadh
1457          1         L                Tertiary and Services  Riyadh
1458          1         L                Tertiary and Services  Riyadh
1462          1         L      Healthcare and Pharmaceuticals   Riyadh

           city  benefits  contract  positions  exper  gender  Salary
7     AR RIYADH         0         1          5      0       2  4000.0
12    AR RIYADH         0         1          1      2       0  5000.0
15    AR RIYADH         0         1          1      0       1  5000.0
19       JEDDAH         0         1          1      0       2  4000.0
20    AR RIYADH         0         1          1      0       0  5500.0
...         ...       ...       ...        ...    ...     ...     ...
1454     MALHAM         0         1          1      0       0  4000.0
1455     MALHAM         0         1          1      0       0  4000.0
1457     MALHAM         0         1          2      0       2  4000.0
1458     MALHAM         0         1          2      0       0  4000.0
1462  AR RIYADH         0         1          5      0       2  7000.0

[368 rows x 14 columns]

In [ ]:
df = data.copy()
df.columns = df.columns.str.strip().str.lower()
print(df.columns)

Index(['job_title', 'job_date', 'comp_name', 'comp_type', 'comp_size',
       'eco_activity', 'region', 'city', 'benefits', 'contract', 'positions',
       'exper', 'gender', 'salary'],
      dtype='object')

In [ ]:
text_columns = df.select_dtypes(include="object").columns

for col in text_columns:
    df[col] = df[col].str.strip()

In [ ]:
print("Duplicates after text cleaning:", df.duplicated().sum())

Duplicates after text cleaning: 83

In [ ]:
df = df.drop_duplicates(keep="first")
print("Duplicates after removal:", df.duplicated().sum())

Duplicates after removal: 0

In [ ]:
# converting date type to date instead of object
df["job_date"] = pd.to_datetime(
    df["job_date"],
    errors="coerce")
print(df["job_date"].dtype)

datetime64[ns]

In [ ]:
# checking the conversion of the dates
print("Invalid dates:", df["job_date"].isna().sum())
print("Earliest date:", df["job_date"].min())
print("Latest date:", df["job_date"].max())

Invalid dates: 0
Earliest date: 2022-10-01 00:00:00
Latest date: 2023-01-23 00:00:00

In [ ]:
print(df["positions"].unique())
print(df[df["positions"] <= 0])

[ 1  3  2 10  6  5  4  7 15 50 20 25 46  8 30  9]
Empty DataFrame
Columns: [job_title, job_date, comp_name, comp_type, comp_size, eco_activity, region, city, benefits, contract, positions, exper, gender, salary]
Index: []

In [ ]:
# checking for negative values
print(df[df["exper"] < 0])

Empty DataFrame
Columns: [job_title, job_date, comp_name, comp_type, comp_size, eco_activity, region, city, benefits, contract, positions, exper, gender, salary]
Index: []

In [ ]:
print("Final rows:", len(df))
print("Final columns:", len(df.columns))

print("\nMissing values:")
print(df.isnull().sum())

print("\nDuplicate rows:")
print(df.duplicated().sum())

print("\nData types:")
print(df.dtypes)

Final rows: 1387
Final columns: 14

Missing values:
job_title       0
job_date        0
comp_name       0
comp_type       0
comp_size       0
eco_activity    0
region          0
city            0
benefits        0
contract        0
positions       0
exper           0
gender          0
salary          0
dtype: int64

Duplicate rows:
0

Data types:
job_title               object
job_date        datetime64[ns]
comp_name               object
comp_type                int64
comp_size               object
eco_activity            object
region                  object
city                    object
benefits                 int64
contract                 int64
positions                int64
exper                    int64
gender                   int64
salary                 float64
dtype: object

In [ ]:
# Select specific job titles from job_title column

print(df["job_title"].value_counts())

job_title
Analyst                     222
Salesperson                 188
Manager                     126
Accountant                  123
Technician                   97
Switchboard Operator         74
Engineer                     70
Receptionist                 62
Secretary                    47
Administrative Assistant     45
Teacher/Trainer              34
Driver                       29
HR Specialist                28
Writer                       22
Electrician                  22
Artist                       21
Lawyer                       18
Clerk                        17
Dentist                      14
Developer                    14
Security Guard               11
Pharmacist                   11
Auditor                      10
Debt Collector                8
Chef                          8
Chemist                       6
Constructor                   6
Health Assistant              6
Doctor                        6
Florist                       5
Carpenter                     5
Real Estate Broker            4
Worker                        4
Mechanic                      4
CEO                           4
Barista                       3
Hair Stylist                  3
Nurse                         2
Translator                    2
Pilot                         2
Lab Technician                1
Licensing Officer             1
Tailor                        1
Scientist                     1
Name: count, dtype: int64

In [ ]:
df.columns

Index(['job_title', 'job_date', 'comp_name', 'comp_type', 'comp_size',
       'eco_activity', 'region', 'city', 'benefits', 'contract', 'positions',
       'exper', 'gender', 'salary'],
      dtype='object')

In [ ]:
# Removing extra columns
df = df.drop(columns=['comp_type','comp_size' ,'benefits',
                 'contract','positions','gender'])
print(df.columns)

Index(['job_title', 'job_date', 'comp_name', 'eco_activity', 'region', 'city',
       'exper', 'salary'],
      dtype='object')

In [ ]:
# UNIFY COLUMN NAMES with other datasets
df = df.rename(columns={
    'comp_name': 'company_name',
    'eco_activity': 'industry',
    'contract': 'contract_type',
    'exper': 'experience_years',
    'job_date':'job_posted_date'

})

print(df.columns)

Index(['job_title', 'job_posted_date', 'company_name', 'industry', 'region',
       'city', 'experience_years', 'salary'],
      dtype='object')

In [ ]:
# Adding new columns to unify the dataset with other datasets

df[['url', 'company_url',
    'employment_type','job_category','description' ]] = None


df['source_job_id'] = range(1, len(df) + 1)
df['country'] = 'Saudi Arabia'
df['job_source'] = 'Jadarat.com'
df['workplace_type'] = 'Onsite'
df['is_salary_disclosed'] = df['salary'].notna()
df['job_status'] = 'Closed'
df['collected_at'] = datetime.now().strftime('%Y-%m-%d %H:%M:%S')

df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1387 entries, 0 to 1469
Data columns (total 20 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   job_title            1387 non-null   object
 1   job_posted_date      1387 non-null   datetime64[ns]
 2   company_name         1387 non-null   object
 3   industry             1387 non-null   object
 4   region               1387 non-null   object
 5   city                 1387 non-null   object
 6   experience_years     1387 non-null   int64
 7   salary               1387 non-null   float64
 8   url                  0 non-null      object
 9   company_url          0 non-null      object
 10  employment_type      0 non-null      object
 11  job_category         0 non-null      object
 12  description          0 non-null      object
 13  source_job_id        1387 non-null   int64
 14  country              1387 non-null   object
 15  job_source           1387 non-null   object
 16  workplace_type       1387 non-null   object
 17  is_salary_disclosed  1387 non-null   bool
 18  job_status           1387 non-null   object
 19  collected_at         1387 non-null   object
dtypes: bool(1), datetime64[ns](1), float64(1), int64(2), object(15)
memory usage: 218.1+ KB

In [ ]:
# Removing salary column after comsidering "is_salary_discloed" column

df.drop(columns=['salary'], inplace=True)

In [ ]:
# Checking new updates
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1387 entries, 0 to 1469
Data columns (total 19 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   job_title            1387 non-null   object
 1   job_posted_date      1387 non-null   datetime64[ns]
 2   company_name         1387 non-null   object
 3   industry             1387 non-null   object
 4   region               1387 non-null   object
 5   city                 1387 non-null   object
 6   experience_years     1387 non-null   int64
 7   url                  0 non-null      object
 8   company_url          0 non-null      object
 9   employment_type      0 non-null      object
 10  job_category         0 non-null      object
 11  description          0 non-null      object
 12  source_job_id        1387 non-null   int64
 13  country              1387 non-null   object
 14  job_source           1387 non-null   object
 15  workplace_type       1387 non-null   object
 16  is_salary_disclosed  1387 non-null   bool
 17  job_status           1387 non-null   object
 18  collected_at         1387 non-null   object
dtypes: bool(1), datetime64[ns](1), int64(2), object(15)
memory usage: 207.2+ KB

In [ ]:
# Rearrange the columns
df = df[
    [
        'source_job_id',
        'job_title',
        'url',
        'company_name',
        'company_url',
        'city',
        'region',
        'country',
        'employment_type',
        'workplace_type',
        'experience_years',
        'job_category',
        'industry',
        'is_salary_disclosed',
        'job_source',
        'job_posted_date',
        'job_status',
        'collected_at',
        'description'
    ]
]

In [ ]:
# Save the cleaned dataset
df.to_csv("jadarat_cleaned.csv", index=False)